### ISSUE TITLE
Explorer: Blank screen when trying to view application

### ISSUE THREAD

**Issue by MasterHW** [gitcoinco/MACI_QF#15]
in the explorer when I open an application to the test round it produces an error and does not render this page. this only happened after I connected my wallet.

https://www.loom.com/share/866ec3a1de894983844b82cd69049098

**Comment by 0xKurt** [comment]
![Image](https://github.com/gitcoinco/MACI_QF/assets/22886639/c818d6ad-2d62-4ca3-b78b-092b273ca412)

Steps to repro:
From round - https://maci-qf-explorer-xi.vercel.app/#/round/11155111/325
Click on Fancy Protocol project 
See blank page

**Comment by bhargavaparoksham** [comment]
This issue is resolved.

**Comment by MasterHW** [comment]
I'm still experiencing this
https://www.loom.com/share/f3e3057b8d63409084782fb57608fe7a
